


export const labels = ["Urea","DAP","14-35-14","28-28","17-17-17","20-20","10-26-26"]

// Image paths for each output fertilizer
export const label_image_paths = {
  "Urea": "/images/fertilizers/urea.jpg",
  "DAP": "/images/fertilizers/DAP.jpg",
  "14-35-14": "/images/fertilizers/default.jpg",
  "28-28": "/images/fertilizers/default.jpg",
  "17-17-17": "/images/fertilizers/default.jpg",
  "20-20": "/images/fertilizers/default.jpg",
  "10-26-26": "/images/fertilizers/default.jpg",
};


// Descriptions for each fertilizer predicted by the ML model.
export const output_descriptions = {
  en: {
    "Urea": ` Urea is a type of fertilizer that is made from synthetic nitrogen. It is widely used in agriculture to provide crops with the nitrogen they need to grow and thrive. With a high nitrogen content, urea is an excellent choice for boosting the growth and yield of your crops. Additionally, urea is highly effective in a range of soil types and temperatures, making it a versatile option for any farmer. In terms of phosphorous and humidity, urea is also a top performer, helping to promote strong root growth and overall plant health. So, whether you're growing corn, wheat, soybeans, or even fruit trees, urea is sure to give you the results you're looking for. Plus, with a little bit of humor, let's just say that your crops will be "urea" happy with the added nutrients! `,
    "DAP": ` DAP, or diammonium phosphate, is a type of fertilizer that is commonly used in agriculture to supply plants with essential nutrients, including nitrogen and phosphorous. One of the main reasons to use DAP is that it is highly effective at increasing the nitrogen content in the soil, which is essential for plant growth. Nitrogen is an essential component of chlorophyll, the molecule that allows plants to photosynthesize and convert sunlight into energy. Without enough nitrogen, your plants will be unable to fully utilize the sunlight they receive, resulting in poor growth and reduced yields. Another benefit of DAP is that it can help to improve the soil's structure and texture, making it easier for roots to grow and absorb nutrients. This is especially important in soils that are heavy or compacted, as it can help to loosen the soil and allow water and nutrients to reach the plant's roots more easily. Overall, DAP is a fantastic choice for any farmer looking to improve the health and productivity of their crops. It is suitable for a wide range of crops, including fruit trees, vegetables, and grains, and can be easily applied using a fertilizer spreader or by hand. So why wait? Start using DAP today and watch your crops flourish! `,
    "14-35-14": ` The 14-35-14 is a balanced fertilizer that contains 14% nitrogen, 35% phosphorous, and 14% potassium (also known as "potash"). Phosphorous is necessary for root growth and fruiting, and the 35% phosphorous content in 14-35-14 will help your crops develop strong, healthy roots and produce plenty of fruit. This is especially important for warm-season crops like tomatoes, peppers, and squash. Potassium, or potash, is important for overall plant health and helps plants resist disease. The 14% potash content in 14-35-14 will help keep your crops strong and healthy throughout the growing season. 14-35-14 is a versatile fertilizer that can be used in a wide range of temperatures and humidity levels, so you don't have to worry about those factors. As for soil type, 14-35-14 is suitable for use in most types of soil, including sandy, loamy, and clay soils. It provides the right mix of nutrients for healthy plant growth, and it can be used in a wide range of temperatures, humidity levels, and soil types. And with the right combination of nitrogen, phosphorous, and potash, you can grow a wide range of crops, including leafy greens, tomatoes, peppers, squash, and more. Plus, it's always good to have a little bit of humor on the farm, right `,
    "28-28": ` 28-28 fertilizer is a type of balanced fertilizer that contains equal amounts of nitrogen and phosphorus, both of which are essential nutrients for plant growth. As a farmer, you'll be happy to know that using 28-28 fertilizer can help improve the nutrient content of your soil, providing your crops with the nourishment they need to thrive. Nitrogen is important for promoting leafy growth, while phosphorus is necessary for root development and fruit production. But that's not all! 28-28 fertilizer is also great for a wide range of soil types and climates, making it a versatile choice for any farmer. Whether you're dealing with sandy soil, clay soil, or something in between, 28-28 can help give your crops the boost they need. And because it's balanced, you won't have to worry about overloading your soil with excess nutrients, which can lead to nutrient imbalances and reduced crop yields. It's a great choice for a wide range of crops, including fruits, vegetables, grains, and more. Just remember to follow the recommended application rates and always use protective equipment when handling fertilizers. Happy farming! `,
    "17-17-17": ` 17-17-17 is a balanced fertilizer, meaning it contains equal amounts of the three primary macronutrients: nitrogen, phosphorous, and potassium. These nutrients are essential for plant growth and development, and they work together to support healthy plants. Now, as a farmer, you already have the ideal soil conditions and crop type in mind, and 17-17-17 fertilizer is the perfect match for you. The balanced nutrient ratio ensures that your crops will have access to the exact nutrients they need at the right stages of growth. Plus, the added humidity-regulating properties of 17-17-17 will help your plants thrive in any weather conditions. Not to mention, this fertilizer is extremely versatile and can be used on a wide range of crops, from leafy greens to fruiting vegetables and even fruit trees. So whether you're looking to grow some juicy watermelons or a field of fragrant lavender, 17-17-17 has you covered. `,
    "20-20": ` 20-20 fertilizer is a balanced fertilizer that contains equal parts of nitrogen, phosphorous, and potassium, also known as NPK. The numbers 20-20 refer to the percentage of these three nutrients that are present in the fertilizer. If you have a soil with a pH level that falls within the neutral range, around 6.5 to 7.5, 20-20 fertilizer will be highly effective at providing the nutrients your crops need to thrive. Additionally, if you have a soil type that is rich in organic matter, the 20-20 fertilizer will work even better, as the nutrients in the fertilizer will be able to easily interact with the organic matter in the soil. Another great reason to use 20-20 fertilizer is that it is highly versatile and can be used on a wide variety of crops and fruit trees. Some examples of crops that do well with 20-20 fertilizer include tomatoes, peppers, squash, and melons. Fruit trees such as apples, pears, and cherries also benefit from the balanced nutrition provided by 20-20 fertilizer. So, in short, if you have a neutral pH soil and a good amount of organic matter, 20-20 fertilizer is a fantastic choice for providing your crops and fruit trees with the nutrients they need to thrive. Plus, with its versatility, you'll be able to use it on a variety of different crops and fruit trees. So why not give it a try and see the amazing results for yourself? Happy farming! `,
    "10-26-26": `  10-26-26 is a balanced blend of macronutrients, including 10% nitrogen, 26% phosphorus, and 26% potassium. These nutrients are essential for healthy plant growth and development. The nitrogen in 10-26-26 will help to promote strong stem and leaf growth, ensuring that your plants are able to photosynthesize efficiently and produce a good yield. The phosphorus in the fertilizer will support root development and help your plants to absorb essential minerals from the soil. Finally, the potassium will help to improve the overall health and hardiness of your crops, making them more resistant to stress and pests. But it's not just about the nutrients! The 10-26-26 formula is also specially formulated to be effective in a variety of soil types and climates. So whether you're growing in sandy soil, clay soil, or somewhere in between, this fertilizer will provide your crops with the nutrients they need to thrive. And with a little bit of TLC and some proper watering and weeding, you'll be well on your way to a bumper crop of delicious fruits and vegetables. So go ahead, give 10-26-26 a try on your farm. Your crops (and taste buds) will thank you! `,
  },
  hi: {
    "Urea": `यूरिया एक प्रकार का उर्वरक है जो सिंथेटिक नाइट्रोजन से बनाया जाता है। फसलों को उगने और फलने-फूलने के लिए आवश्यक नाइट्रोजन प्रदान करने के लिए कृषि में इसका व्यापक रूप से उपयोग किया जाता है। उच्च नाइट्रोजन सामग्री के साथ, यूरिया आपकी फसलों की वृद्धि और उपज को बढ़ाने के लिए एक उत्कृष्ट विकल्प है। इसके अतिरिक्त, यूरिया विभिन्न प्रकार की मिट्टी और तापमान में अत्यधिक प्रभावी है, जो इसे किसी भी किसान के लिए एक बहुमुखी विकल्प बनाता है। फॉस्फोरस और आर्द्रता के मामले में, यूरिया भी एक शीर्ष प्रदर्शनकर्ता है, जो मजबूत जड़ विकास और समग्र पौधों के स्वास्थ्य को बढ़ावा देने में मदद करता है। इसलिए, चाहे आप मक्का, गेहूं, सोयाबीन, या यहां तक ​​कि फलों के पेड़ उगा रहे हों, यूरिया निश्चित रूप से आपको वह परिणाम देगा जो आप चाहते हैं। साथ ही, थोड़े हास्य के साथ, मान लें कि अतिरिक्त पोषक तत्वों से आपकी फसलें "यूरिया" से खुश होंगी!`,
    "DAP": `डीएपी, या डायमोनियम फॉस्फेट, एक प्रकार का उर्वरक है जिसका उपयोग आमतौर पर कृषि में पौधों को नाइट्रोजन और फॉस्फोरस सहित आवश्यक पोषक तत्व प्रदान करने के लिए किया जाता है। डीएपी का उपयोग करने का एक मुख्य कारण यह है कि यह मिट्टी में नाइट्रोजन की मात्रा बढ़ाने में अत्यधिक प्रभावी है, जो पौधों के विकास के लिए आवश्यक है। नाइट्रोजन क्लोरोफिल का एक आवश्यक घटक है, वह अणु जो पौधों को प्रकाश संश्लेषण करने और सूर्य के प्रकाश को ऊर्जा में परिवर्तित करने की अनुमति देता है। पर्याप्त नाइट्रोजन के बिना, आपके पौधे प्राप्त सूर्य के प्रकाश का पूरी तरह से उपयोग करने में असमर्थ होंगे, जिसके परिणामस्वरूप खराब विकास होगा और पैदावार कम होगी। डीएपी का एक अन्य लाभ यह है कि यह मिट्टी की संरचना और बनावट में सुधार करने में मदद कर सकता है, जिससे जड़ों को बढ़ने और पोषक तत्वों को अवशोषित करने में आसानी होती है। यह उन मिट्टी में विशेष रूप से महत्वपूर्ण है जो भारी या सघन हैं, क्योंकि यह मिट्टी को ढीला करने में मदद कर सकता है और पानी और पोषक तत्वों को पौधे की जड़ों तक अधिक आसानी से पहुंचने दे सकता है। कुल मिलाकर, अपनी फसलों के स्वास्थ्य और उत्पादकता में सुधार चाहने वाले किसी भी किसान के लिए डीएपी एक शानदार विकल्प है। यह फलों के पेड़ों, सब्जियों और अनाज सहित फसलों की एक विस्तृत श्रृंखला के लिए उपयुक्त है, और इसे उर्वरक स्प्रेडर का उपयोग करके या हाथ से आसानी से लगाया जा सकता है। तो इंतज़ार क्यों करें? आज ही डीएपी का उपयोग शुरू करें और अपनी फसलों को फलते-फूलते देखें!`,
    "14-35-14": `14-35-14 एक संतुलित उर्वरक है जिसमें 14% नाइट्रोजन, 35% फॉस्फोरस और 14% पोटेशियम (जिसे "पोटाश" भी कहा जाता है) होता है। फास्फोरस जड़ वृद्धि और फलने के लिए आवश्यक है, और 14-35-14 में 35% फास्फोरस सामग्री आपकी फसलों को मजबूत, स्वस्थ जड़ें विकसित करने और प्रचुर मात्रा में फल पैदा करने में मदद करेगी। यह टमाटर, मिर्च और स्क्वैश जैसी गर्म मौसम की फसलों के लिए विशेष रूप से महत्वपूर्ण है। पोटेशियम, या पोटाश, पौधों के समग्र स्वास्थ्य के लिए महत्वपूर्ण है और पौधों को रोग प्रतिरोधी बनाने में मदद करता है। 14-35-14 में 14% पोटाश सामग्री पूरे बढ़ते मौसम में आपकी फसलों को मजबूत और स्वस्थ रखने में मदद करेगी। 14-35-14 एक बहुमुखी उर्वरक है जिसका उपयोग तापमान और आर्द्रता के स्तर की एक विस्तृत श्रृंखला में किया जा सकता है, इसलिए आपको उन कारकों के बारे में चिंता करने की ज़रूरत नहीं है। मिट्टी के प्रकार के लिए, 14-35-14 अधिकांश प्रकार की मिट्टी में उपयोग के लिए उपयुक्त है, जिसमें रेतीली, दोमट और चिकनी मिट्टी शामिल हैं। यह स्वस्थ पौधों के विकास के लिए पोषक तत्वों का सही मिश्रण प्रदान करता है, और इसका उपयोग तापमान, आर्द्रता स्तर और मिट्टी के प्रकारों की एक विस्तृत श्रृंखला में किया जा सकता है। और नाइट्रोजन, फॉस्फोरस और पोटाश के सही संयोजन के साथ, आप पत्तेदार साग, टमाटर, मिर्च, स्क्वैश और बहुत कुछ सहित कई प्रकार की फसलें उगा सकते हैं। साथ ही, फ़ार्म पर थोड़ा-बहुत हास्य होना हमेशा अच्छा होता है, ठीक है`,
    "28-28": `28-28 उर्वरक एक प्रकार का संतुलित उर्वरक है जिसमें नाइट्रोजन और फास्फोरस समान मात्रा में होते हैं, जो दोनों पौधों के विकास के लिए आवश्यक पोषक तत्व हैं। एक किसान के रूप में, आपको यह जानकर खुशी होगी कि 28-28 उर्वरक का उपयोग करने से आपकी मिट्टी की पोषक तत्व सामग्री में सुधार करने में मदद मिल सकती है, जिससे आपकी फसलों को पोषण मिलेगा जो उन्हें बढ़ने के लिए आवश्यक है। नाइट्रोजन पत्ती वृद्धि को बढ़ावा देने के लिए महत्वपूर्ण है, जबकि फास्फोरस जड़ विकास और फल उत्पादन के लिए आवश्यक है। लेकिन इतना ही नहीं! 28-28 उर्वरक विभिन्न प्रकार की मिट्टी और जलवायु के लिए भी बढ़िया है, जो इसे किसी भी किसान के लिए एक बहुमुखी विकल्प बनाता है। चाहे आप रेतीली मिट्टी, चिकनी मिट्टी या इनके बीच की किसी चीज़ से निपट रहे हों, 28-28 आपकी फसलों को आवश्यक बढ़ावा देने में मदद कर सकता है। और क्योंकि यह संतुलित है, आपको अपनी मिट्टी में अतिरिक्त पोषक तत्वों की अधिकता के बारे में चिंता करने की ज़रूरत नहीं होगी, जिससे पोषक तत्वों में असंतुलन हो सकता है और फसल की पैदावार कम हो सकती है। यह फलों, सब्जियों, अनाजों और अन्य सहित फसलों की एक विस्तृत श्रृंखला के लिए एक बढ़िया विकल्प है। बस अनुशंसित आवेदन दरों का पालन करना याद रखें और उर्वरकों को संभालते समय हमेशा सुरक्षात्मक उपकरणों का उपयोग करें। खुशहाल खेती!`,
    "17-17-17": `17-17-17 एक संतुलित उर्वरक है, जिसका अर्थ है कि इसमें तीन प्राथमिक मैक्रोन्यूट्रिएंट्स की समान मात्रा होती है: नाइट्रोजन, फॉस्फोरस और पोटेशियम। ये पोषक तत्व पौधों की वृद्धि और विकास के लिए आवश्यक हैं, और वे स्वस्थ पौधों को समर्थन देने के लिए मिलकर काम करते हैं। अब, एक किसान के रूप में, आपके मन में पहले से ही आदर्श मिट्टी की स्थिति और फसल का प्रकार है, और 17-17-17 उर्वरक आपके लिए एकदम उपयुक्त है। संतुलित पोषक तत्व अनुपात यह सुनिश्चित करता है कि आपकी फसलों को विकास के सही चरणों में आवश्यक सटीक पोषक तत्व उपलब्ध होंगे। साथ ही, 17-17-17 के अतिरिक्त आर्द्रता-विनियमन गुण आपके पौधों को किसी भी मौसम की स्थिति में पनपने में मदद करेंगे। कहने की जरूरत नहीं है, यह उर्वरक बेहद बहुमुखी है और इसका उपयोग पत्तेदार सब्जियों से लेकर फलदार सब्जियों और यहां तक ​​कि फलों के पेड़ों तक, विभिन्न प्रकार की फसलों पर किया जा सकता है। तो चाहे आप कुछ रसीले तरबूज़ उगाना चाह रहे हों या सुगंधित लैवेंडर का खेत, 17-17-17 आपके लिए उपलब्ध है।`,
    "20-20": `20-20 उर्वरक एक संतुलित उर्वरक है जिसमें नाइट्रोजन, फॉस्फोरस और पोटेशियम के बराबर भाग होते हैं, जिन्हें एनपीके भी कहा जाता है। संख्या 20-20 इन तीन पोषक तत्वों के प्रतिशत को दर्शाती है जो उर्वरक में मौजूद हैं। यदि आपके पास पीएच स्तर वाली मिट्टी है जो तटस्थ सीमा के भीतर आती है, लगभग 6.5 से 7.5, तो 20-20 उर्वरक आपकी फसलों को पनपने के लिए आवश्यक पोषक तत्व प्रदान करने में अत्यधिक प्रभावी होंगे। इसके अतिरिक्त, यदि आपके पास ऐसी मिट्टी है जो कार्बनिक पदार्थों से समृद्ध है, तो 20-20 उर्वरक और भी बेहतर काम करेगा, क्योंकि उर्वरक में मौजूद पोषक तत्व मिट्टी में कार्बनिक पदार्थों के साथ आसानी से बातचीत करने में सक्षम होंगे। 20-20 उर्वरक का उपयोग करने का एक और बड़ा कारण यह है कि यह अत्यधिक बहुमुखी है और इसका उपयोग विभिन्न प्रकार की फसलों और फलों के पेड़ों पर किया जा सकता है। 20-20 उर्वरक के साथ अच्छी उपज देने वाली फसलों के कुछ उदाहरणों में टमाटर, मिर्च, स्क्वैश और खरबूजे शामिल हैं। सेब, नाशपाती और चेरी जैसे फलों के पेड़ भी 20-20 उर्वरक द्वारा प्रदान किए गए संतुलित पोषण से लाभान्वित होते हैं। तो, संक्षेप में, यदि आपके पास तटस्थ पीएच वाली मिट्टी और अच्छी मात्रा में कार्बनिक पदार्थ हैं, तो आपकी फसलों और फलों के पेड़ों को पनपने के लिए आवश्यक पोषक तत्व प्रदान करने के लिए 20-20 उर्वरक एक शानदार विकल्प है। साथ ही, इसकी बहुमुखी प्रतिभा के कारण, आप इसे विभिन्न फसलों और फलों के पेड़ों पर उपयोग करने में सक्षम होंगे। तो क्यों न इसे आज़माएं और आश्चर्यजनक परिणाम स्वयं देखें? खुशहाल खेती!`,
    "10-26-26": `10-26-26 मैक्रोन्यूट्रिएंट्स का एक संतुलित मिश्रण है, जिसमें 10% नाइट्रोजन, 26% फॉस्फोरस और 26% पोटेशियम शामिल हैं। ये पोषक तत्व स्वस्थ पौधों की वृद्धि और विकास के लिए आवश्यक हैं। 10-26-26 में नाइट्रोजन मजबूत तने और पत्ती के विकास को बढ़ावा देने में मदद करेगा, जिससे यह सुनिश्चित होगा कि आपके पौधे कुशलता से प्रकाश संश्लेषण करने और अच्छी उपज देने में सक्षम हैं। उर्वरक में मौजूद फास्फोरस जड़ विकास में सहायता करेगा और आपके पौधों को मिट्टी से आवश्यक खनिजों को अवशोषित करने में मदद करेगा। अंत में, पोटेशियम आपकी फसलों के समग्र स्वास्थ्य और कठोरता को बेहतर बनाने में मदद करेगा, जिससे उन्हें तनाव और कीटों के प्रति अधिक प्रतिरोधी बनाया जा सकेगा। लेकिन यह सिर्फ पोषक तत्वों के बारे में नहीं है! 10-26-26 फॉर्मूला भी विभिन्न प्रकार की मिट्टी और जलवायु में प्रभावी होने के लिए विशेष रूप से तैयार किया गया है। तो चाहे आप रेतीली मिट्टी, चिकनी मिट्टी, या बीच में कहीं उग रहे हों, यह उर्वरक आपकी फसलों को वे पोषक तत्व प्रदान करेगा जिनकी उन्हें वृद्धि के लिए आवश्यकता है। और थोड़ी सी टीएलसी और कुछ उचित पानी और निराई के साथ, आप स्वादिष्ट फलों और सब्जियों की भरपूर फसल की ओर अग्रसर होंगे। तो आगे बढ़ें, 10-26-26 को अपने फार्म पर आज़माएँ। आपकी फसलें (और स्वाद कलिकाएँ) आपको धन्यवाद देंगी!`,
  }
}
